title: COCO__ReM
description: Your site description
baseurl: "/COCO__ReM" # Adjust this based on your project structure
url: "https://github.com/Shweta-singh1//COCO__ReM"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - explore1
  - node_modules
  - vendor
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - .DS_Store

# Settings for kramdown, the Markdown parser
kramdown:
  input: GFM
  syntax_highlighter: rouge
